Remove MultilingualField in education
svthalia/concrexit pull request #1273
Opened 2020-09-30 14:04 UTC by pingiun

Related to #1200 
Summary

Remove MultilingualField in announcements
How to test

Everything should still work as before

2020-10-01 20:07 UTC, se-bastiaan requested changes
You're forgetting createfixtures

2020-10-05 20:26 UTC, pingiun commented
> You're forgetting createfixtures

Fixed

2020-10-12 19:07 UTC, se-bastiaan approved these changes

2020-10-12 19:07 UTC, merged

2020-11-09 20:00 UTC, Legosteen11 commented
Seems to cause this error when loading /education/courses

![image](https://user-images.githubusercontent.com/6750407/98590012-77982880-22ce-11eb-9478-80e5357f6c84.png)

```
FieldError at /education/courses/
Cannot resolve keyword 'name_en' into field. Choices are: categories, course, course_code, ec, exam, id, name, old_courses, since, summary, until
```