Add country field to partner
svthalia/concrexit pull request #1420
Opened 2020-11-23 19:33 UTC by Jorritboer

Closes #1348 

### Summary
Made partner address values the same as in users.

### How to test
Steps to test the changes you made:
1. Go to partner admin
2. Set the country to a foreign country
3. Go to the partner page
4. See the partner's country and it's location on the map

2020-11-23 20:24 UTC, pingiun commented
deploy review

2020-11-23 20:40 UTC, pingiun commented
deploy review

2020-11-23 21:08 UTC, JobDoesburg submitted a review, later dismissed

2020-11-23 21:42 UTC, se-bastiaan commented on website/partners/templates/partners/partner.html
> +                        {{ partner.city }} <br />
```suggestion
                        {{ partner.city }}<br />
```

2020-11-23 21:53 UTC, se-bastiaan commented on website/partners/templates/partners/partner.html
> +                            {{ partner.get_country_display }}
For international students it may actually be useful to always show the country, since they do not know all the Dutch cities?

2020-11-23 21:54 UTC, se-bastiaan requested changes
.

2020-11-30 20:58 UTC, se-bastiaan approved these changes

2020-12-01 07:18 UTC, merged