Move API v1 to subpackages
svthalia/concrexit pull request #1429
Opened 2020-11-27 14:32 UTC by se-bastiaan

### Summary
This PR moves all existing code that we have for API endpoints to v1 packages inside the Django apps.
It also introduces basic functionality for API v2 that we do not want introduced into v1 and vice versa. Examples are the pagination and authentication tokens.

### How to test
Steps to test the changes you made:
1. Check that all APIs are still available in the docs `/api/docs`
2. Test some of the APIs
3. Profit

2020-12-05 16:45 UTC, 9Y0 requested changes
Going to `/api/docs` results in an error: `Reverse for 'schema-v2' not found. 'schema-v2' is not a valid view function or pattern name.`

2020-12-07 21:17 UTC, pingiun commented
deploy review

2020-12-07 21:25 UTC, pingiun approved these changes

2020-12-07 21:25 UTC, merged

2020-12-07 21:48 UTC, 9Y0 commented
Why exactly is this one merged? `/api/docs` still crashes, also on the review environment