Remove Dutch website logo
svthalia/concrexit pull request #1434
Opened 2020-12-01 14:09 UTC by ColonelPhantom

Closes #1357 (?)

### Summary
I have removed the code to localize the logo based on the language, since there is only 1 language now. The issue refers to more (Dutch) localization, but I am unsure what it is referring to. Is it all the references to `{% trans "text" %}`?

### How to test
Steps to test the changes you made:
1. Load any page

I am not entirely sure the renamed SVGs aren't used elsewhere, but some quick `ripgrep`-ing didn't seem to indicate so.

2020-12-01 14:53 UTC, se-bastiaan commented
I think that @JobDoesburg referred to the use of the LANGUAGE_CODE in the file. https://github.com/svthalia/concrexit/blob/master/website/thaliawebsite/templates/base.html#L4

2020-12-04 19:22 UTC, se-bastiaan requested changes
See previous comment.

2020-12-14 19:43 UTC, ColonelPhantom commented
I have removed all references to `LANGUAGE_CODE`, including the entire `change-language-form`, and took the opportunity to remove both `change-language-form` and `language-switcher` from the JS and CSS.

2020-12-14 19:57 UTC, se-bastiaan approved these changes

2020-12-14 19:58 UTC, merged