Fix sorting by payments in events admin
svthalia/concrexit pull request #1456
Opened 2020-12-10 18:48 UTC by pingiun

Closes #1419

### Summary
We now use the sortvalue sorter for both the date and the payment

### How to test
Steps to test the changes you made:
1. Go to event with payments
2. Sort based on payments
3. Check if sorting changes the order

2020-12-10 21:59 UTC, se-bastiaan commented
deploy review

2020-12-10 22:17 UTC, se-bastiaan commented
remove review

2020-12-10 22:18 UTC, se-bastiaan requested changes
When you change the value of the payment the sorting won't work properly until the page is refreshed.

2020-12-11 12:42 UTC, pingiun commented
This makes sense, I guess I'll have to fix the payment parser then

2020-12-11 19:31 UTC, se-bastiaan commented
Well it is weird because `$('table').trigger('update');` should take care of the sorter update.

2020-12-12 16:07 UTC, se-bastiaan commented
deploy review

2020-12-12 17:17 UTC, pingiun commented
This seems to work great on the reviewhost

2020-12-12 18:03 UTC, se-bastiaan approved these changes

2020-12-12 18:03 UTC, se-bastiaan commented
remove review

2020-12-12 18:04 UTC, merged