Refactor settings
svthalia/concrexit pull request #1459
Opened 2020-12-13 17:20 UTC by pingiun

### Summary
Put all the settings in one file for clarity

### How to test
Nothing should be changed, so if the tests and running the website work it should be fine

2020-12-13 19:40 UTC, pingiun commented
I have no clue why building the docs goes wrong, it totally works locally

2020-12-13 22:31 UTC, se-bastiaan commented
It seems to be expecting a host for postges when building the docs.

Anyways I find this really hard to correctly review but the idea seems good to me.

2020-12-14 20:41 UTC, lukovdm requested changes

2020-12-14 20:41 UTC, lukovdm commented on website/thaliawebsite/settings.py
> +def setting(*, local, production, staging=_NOT_SET, testing=_NOT_SET):
It would be nice to make it a bit clearer what happens when staging or testing is not set

2020-12-14 20:41 UTC, lukovdm commented on website/thaliawebsite/settings.py
> +def from_env(
It would be nice to make it a bit clearer what happens when staging or testing is not set

2020-12-17 12:09 UTC, pingiun commented
Changed to draft because I want to change the nix configuration to go along with this

2020-12-19 12:54 UTC, pingiun commented on README.md
> +If you use Docker, please look at [this part](#docker) of the README.
This needs to be removed

2020-12-19 12:54 UTC, pingiun commented on website/thaliawebsite/templates/base.html
> +                <source srcset="{% static 'img/logo-.svg' %}" media="(prefers-color-scheme: light)">
Remove dash

2020-12-19 13:08 UTC, Legosteen11 submitted a review, later dismissed

2020-12-21 17:36 UTC, se-bastiaan approved these changes

2020-12-24 15:53 UTC, merged