Added the 'too late to cancel without paying fine'-message to the API…
svthalia/concrexit pull request #1492
Opened 2021-01-04 20:34 UTC by LCKnol

…, so it doesn't have to be hardcoded in the app anymore.

Closes #1383 

### Summary
The message that's shown when cancellation isn't possible without paying a fine can now be requested from the API.

### How to test
Steps to test the changes you made:
1. Make sure you're registered for an event for which the registration deadline has already passed 
2. Go to thalia.nu/api/v1/events/1/
2. The message is shown at the bottom: "cancellation isn't possible anymore without..."
3. Go to thalia.nu/events/1/
4. The same message is also shown here

2021-01-31 13:03 UTC, se-bastiaan commented on website/events/templates/events/event.html
> +                                                {{ no_cancellation }}
Apparently this is not working, since the tests are failing on this text not showing up.

2021-01-31 13:04 UTC, se-bastiaan requested changes

2021-01-31 13:04 UTC, se-bastiaan commented on website/events/models/event.py
> +        return (
I would put the translation in the text here instead of the view, that would make it available in the API too

2021-02-23 09:07 UTC, se-bastiaan commented on website/events/tests/test_views.py
> +        print(response.rendered_content)
Not sure if this print belongs here? :p

2021-02-23 21:38 UTC, LCKnol commented on website/events/tests/test_views.py
> +        print(response.rendered_content)
oops, forgot about that!

2021-02-24 08:28 UTC, se-bastiaan commented on website/events/models/event.py
> +        return (
@LCKnol this is still an improvement I think would be good, if you think it is useless just let me know.

2021-03-01 20:31 UTC, se-bastiaan commented on website/events/templates/events/event.html
> +                                                {{ no_cancellation }}
There is no translation here anymore

2021-03-01 20:32 UTC, se-bastiaan commented on website/events/models/event.py
> +        return (
```suggestion
        return _(
```

2021-03-01 20:33 UTC, se-bastiaan commented on website/events/templates/events/event.html
>                                              {% endblocktrans %}
```suggestion
                                            {{ event.cancel_too_late_message }}
```

2021-03-01 22:09 UTC, se-bastiaan approved these changes

2021-03-01 22:09 UTC, merged