Add calendar coloring based on registration
svthalia/concrexit pull request #1551
Opened 2021-02-22 20:14 UTC by ColonelPhantom

Closes #1116

### Summary

I implemented changes in the calendar view, so that the colours of the event indicators/backgrounds are a lot richer:

- As in #1116, when pending, the event clearly indicates this (by being yellow).
- Events without registration are also marked clearly, by being magenta. It might be good to think if this is better than it being the same color as either a registered or registerable event. #1443 would also solve this.
- Events for which you are registered become green.
- Events with closed registration are red. This is rather hard to distinguish from an unpublished event, which is also red. It might be wise to give another color to one of these.

Here are some screenshots:
![screen_2021-02-22-20:56:03](https://user-images.githubusercontent.com/7569492/108763880-314f9800-7552-11eb-95d3-7877cf4edf56.png)
![screen_2021-02-22-20:56:09](https://user-images.githubusercontent.com/7569492/108763887-3280c500-7552-11eb-9478-73f5d72349c5.png)
![screen_2021-02-22-20:56:30](https://user-images.githubusercontent.com/7569492/108763898-357bb580-7552-11eb-835b-afab636cf0b0.png)
![screen_2021-02-22-20:57:10](https://user-images.githubusercontent.com/7569492/108763905-37457900-7552-11eb-880f-065befcc5015.png)

### How to test

- The main functionality is easy to test, simply open the event list/calendar view.
- The change modifies the CalendarJS serializer, I am not sure if this is used elsewhere (like in the app). The flattening I did for the class names (to fix the event indicators in the list view, which are even an issue on current production), might break anything else that depends on it.

2021-02-23 13:28 UTC, se-bastiaan commented
I think your changes to the serializer are fine. What am not sure about if is our members will still  understand all these colours. I am having a hard time understanding it without reading the explanation 😅

2021-03-01 08:52 UTC, JobDoesburg commented
> I think your changes to the serializer are fine. What am not sure about if is our members will still understand all these colours. I am having a hard time understanding it without reading the explanation 😅

I agree with Sebas. Maybe it would be good to use grey tones for unpublished events or events that are closed registration (because you cannot attend them), magenta tones for events that don't have registration or that you are registered for, and we can keep the yellow for waiting list events.

2021-03-15 18:45 UTC, ColonelPhantom commented
I can definitely see what you mean, haha.

Another option might be to add a short description, although it might also be a good idea to have the same color for events that you are registered for and events that do not require registration. Like I said before, #1443 would also help a lot.

2021-03-15 19:11 UTC, se-bastiaan commented
I think it is best to let Job decide the colours for this, I am happy to give my opinion about it :)

2021-03-24 20:13 UTC, JobDoesburg commented
I stay with this suggestion for colors (unless someone disagrees)

> Maybe it would be good to use grey tones for unpublished events or events that are closed registration (because you cannot attend them), magenta tones for events that don't have registration or that you are registered for, and we can keep the yellow for waiting list events.

2021-03-29 19:01 UTC, JobDoesburg requested changes

2021-03-29 19:05 UTC, JobDoesburg commented
So I would say:

- Light grey for unpublished events
- Dark grey for events that are closed registration
- Regular magenta for events that are open (no registration or need registration but still open for registration)
- Darker magenta for events that require registration and that you are actually registered for
- Yellow for events that you are on the waiting list for

2021-03-29 19:43 UTC, ColonelPhantom commented
In the end, I came up with this (unfortunately without seeing the suggestions by @JobDoesburg but I did run this by him):
- the original red for unpublished events (so not modified by me at all)
- transparent gray or no indicator for closed registration
- regular gray for open registration
- magenta for registered
- yellow for pending

![screen_2021-03-29-21:31:59](https://user-images.githubusercontent.com/7569492/112890317-05867b80-90d7-11eb-93da-7796df9b7591.png)
![screen_2021-03-29-21:32:11](https://user-images.githubusercontent.com/7569492/112890322-07503f00-90d7-11eb-8b31-93f6968cf1ee.png)
![screen_2021-03-29-21:33:40](https://user-images.githubusercontent.com/7569492/112890325-091a0280-90d7-11eb-9dca-4200d80d8dcd.png)
![screen_2021-03-29-21:34:55](https://user-images.githubusercontent.com/7569492/112890381-1c2cd280-90d7-11eb-8a95-a46c6cb6d7bf.png)

2021-04-12 19:05 UTC, ColonelPhantom commented
Turns out I forgot to commit and push the color changes, that's done now.

2021-04-14 10:38 UTC, JobDoesburg approved these changes

2021-04-14 10:38 UTC, merged