Add information about registration status to calendar
svthalia/concrexit pull request #1909
Opened 2021-09-07 15:38 UTC by pingiun

Closes #1908 

### Summary
Add information about registration status to calendar

### How to test
Steps to test the changes you made:
1. Go to calendar
2. See that events contain information about your registration status

2021-09-07 15:52 UTC, pingiun commented
I also wanted to add hover text for the colored circle in the list view but the list view doesn't run the `eventRender` hook

2021-09-08 07:08 UTC, se-bastiaan commented on website/events/static/events/js/main.js
> +                let reg_info_elem = document.createElement('div');
Please use camelCase. Like the rest of this file.

2021-09-08 07:08 UTC, se-bastiaan commented on website/events/static/events/js/main.js
> +                let reg_info_elem = document.createElement('div');
This can also be a `const`

2021-09-08 07:10 UTC, se-bastiaan commented
Isn't it possible to just add the extra text to to the title in the serializer with two newlines?

2021-09-08 09:16 UTC, pingiun commented
> Isn't it possible to just add the extra text to to the title in the serializer with two newlines?

Don't think that's a very good idea tbh:

![image](https://user-images.githubusercontent.com/1576660/132482126-c3c126f1-24f9-4d8d-af05-0c4abb746866.png)

2021-09-08 10:20 UTC, se-bastiaan commented
> > Isn't it possible to just add the extra text to to the title in the serializer with two newlines?
> 
> Don't think that's a very good idea tbh:
> 
> ![image](https://user-images.githubusercontent.com/1576660/132482126-c3c126f1-24f9-4d8d-af05-0c4abb746866.png)

Ah didn't think about that

2021-09-09 19:09 UTC, se-bastiaan commented on website/events/api/calendarjs/serializers.py
> +                return f"In waiting list at position {queue_pos}"
Can these strings get put into `_` for localisation, just to keep it consistent.

2021-09-10 15:08 UTC, se-bastiaan commented on website/events/static/events/js/main.js
> +                regInfoElem.classList.add('mt-2');
```suggestion
                regInfoElem.classList.add('mt-2', 'fc-title');
```

2021-09-10 15:10 UTC, se-bastiaan commented on website/events/static/events/js/main.js
> +                regInfoElem.textContent = event.extendedProps.registration_info;
```suggestion
                regInfoElem.title = event.extendedProps.registration_info;
                regInfoElem.textContent = event.extendedProps.registration_info;
```

![image](https://user-images.githubusercontent.com/1799914/132876019-51684f4d-e3c5-4031-a317-1c77f25341d9.png)

2021-09-10 15:18 UTC, se-bastiaan commented
Suggestion for the listview:

```
            eventIndicator.dataset.toggle = 'tooltip';
            eventIndicator.dataset.originalTitle = def.extendedProps.registration_info;
            eventIndicator.title = def.extendedProps.registration_info;
```

and `$('[data-toggle="tooltip"]').tooltip();` at the end of `renderEvents`

2021-09-17 18:50 UTC, se-bastiaan requested changes
See comments

2021-09-20 11:46 UTC, pingiun commented
> Suggestion for the listview:
> 
> ```
>             eventIndicator.dataset.toggle = 'tooltip';
>             eventIndicator.dataset.originalTitle = def.extendedProps.registration_info;
>             eventIndicator.title = def.extendedProps.registration_info;
> ```
> 
> and `$('[data-toggle="tooltip"]').tooltip();` at the end of `renderEvents`

where should this be added?

2021-09-20 13:03 UTC, se-bastiaan commented
> where should this be added?

The list view code. https://github.com/svthalia/concrexit/blob/master/website/events/static/events/js/listview.js#L50

2021-09-20 13:17 UTC, se-bastiaan approved these changes

2021-09-20 13:33 UTC, merged

2021-09-20 18:37 UTC, pingiun commented
This has been reverted in 38.1 because of this:

![image](https://user-images.githubusercontent.com/1576660/134056118-814ad52f-5314-48f4-aad9-c3c937a3aeae.png)