Improve vacancy page layout
svthalia/concrexit pull request #1939
Opened 2021-09-20 19:42 UTC by wdoeland

Closes #1937 

### Summary
Improved the vacancy layout

### How to test
Steps to test the changes you made:
1. Go to `/career/vacancies`
2. Check if you can see locations and tags
3. Maybe add a location and tags to the vacancies in the admin panel
4. Check again

![Screen Shot 2021-09-20 at 21 41 01](https://user-images.githubusercontent.com/6750407/134064847-be6c6cf6-6793-402d-86c6-4dd3fbaa98fd.png)

2021-09-20 20:01 UTC, se-bastiaan commented on website/partners/models.py
> +    keywords = models.TextField(_("keywords"), default="")
This field requires a help text.

2021-10-04 20:05 UTC, se-bastiaan commented on website/partners/models.py
> +    location = models.CharField(_("location"), max_length=255, default="")
```suggestion
    location = models.CharField(_("location"), max_length=255, null=True, blank=True)
```

2021-10-05 17:34 UTC, se-bastiaan requested changes
Something is going wrong with the tests and codestyle, idea looks good!

2021-11-01 19:36 UTC, wdoeland commented
I can't really fix the migrations. I deleted them again and I'm still having the same issue. It says there's conflicting migrations but one of the migrations (0020_auto_20211002_0002) is not even in this branch.

2021-11-01 22:35 UTC, se-bastiaan commented
Did you rebase? Sounds like you didn't and that is what it is expecting from you.

2021-11-03 16:41 UTC, se-bastiaan approved these changes
Rebased it for you

2021-11-03 16:45 UTC, merged