Add promotion model
svthalia/concrexit pull request #2078
Opened 2021-12-14 12:35 UTC by nvoers

Closes #ISSUE

### Summary
A clear and concise description of the changes that you made. What bug did you solve? Or what feature did you add?

### How to test
Steps to test the changes you made:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

2021-12-14 15:00 UTC, JobDoesburg commented on website/promotion/models.py
> +        return super().save(kwargs)
Add a meta class to give translatable model names, plural names and possibly think about custom permissions (default permissions are `add` `change` `delete` and `view` but maybe more advanced permissions are required...)

2021-12-14 15:01 UTC, JobDoesburg commented on website/promotion/templates/requests/new_request_email.txt
> +{% load i18n %}{% blocktrans with request_event_title=request.event.title request_publish_date=request.publish_date request_channel=request.channel%}Hi Paparazcie,
I don't think this `with (...)` is required here as it's not doing anything special

2021-12-15 09:21 UTC, nvoers commented on requirements.txt
> +argon2-cffi==21.1.0; python_version >= "3.5" \
removed the file

2021-12-15 18:30 UTC, se-bastiaan commented on website/events/services.py
> +        member_in_paparazcie = member.get_member_groups().filter(pk=MemberGroup.objects.filter(name = "Paparazcie").pk).count() != 0
+1

2021-12-15 19:09 UTC, JobDoesburg requested changes
Can you edit your PR to allow other maintainers to access your branch? I currently cannot checkout your code to work on it (should be a checkbox somewhere on the right)

2021-12-15 19:09 UTC, JobDoesburg commented on website/promotion/models.py
> +        default = ""
I would make this field `null=True, blank=True`

2021-12-15 19:09 UTC, JobDoesburg commented on website/promotion/models.py
> +        max_length = 200,
I would make this field `null=True, blank=True`

2021-12-15 19:09 UTC, JobDoesburg commented on website/promotion/models.py
> +        max_length = 200,
Also I think 200 chars is too low, google drive urls can get pretty long

2021-12-15 19:09 UTC, JobDoesburg commented on website/promotion/models.py
> +    remarks = HTMLField(("remarks"),)
```suggestion
    remarks = HTMLField(verbose_name=_("remarks"),)
```

2021-12-15 19:09 UTC, JobDoesburg commented on website/promotion/models.py
> +    created_at = models.DateTimeField(
```suggestion
    created_at = models.DateTimeField(
    verbose_name=_("created_at"),
```

2021-12-15 19:09 UTC, JobDoesburg commented on website/promotion/migrations/0006_auto_20211215_1201.py
> +    ]
When all model changes are done, please merge all migrations (remove all of them, re-make them)

2021-12-17 10:55 UTC, JobDoesburg commented
@nvoers sorry I had to rebase and became author of your commits :)

2021-12-17 12:38 UTC, se-bastiaan commented on website/promotion/templates/requests/new_request_email.txt
> +{% load i18n bleach_tags %}{% blocktrans %}Hi Paparazcie,
```suggestion
{% load i18n bleach_tags %}{% blocktrans %}Hi,
```

2021-12-17 13:35 UTC, se-bastiaan submitted a review, later dismissed

2021-12-17 14:25 UTC, JobDoesburg approved these changes

2021-12-17 14:46 UTC, pingiun commented
> @nvoers sorry I had to rebase and became author of your commits :)

A rebase shouldn't change the author, just the committer

2021-12-17 14:49 UTC, JobDoesburg commented
> > @nvoers sorry I had to rebase and became author of your commits :)
> 
> A rebase shouldn't change the author, just the committer

Then I don't know how this happened hahaha

2021-12-17 14:50 UTC, pingiun commented
> > > @nvoers sorry I had to rebase and became author of your commits :)
> > 
> > 
> > A rebase shouldn't change the author, just the committer
> 
> Then I don't know how this happened hahaha

It's correct:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/1576660/146562489-b0c4d662-c13a-44b7-ba8e-de5e429fe8d2.png">

2021-12-17 18:10 UTC, se-bastiaan approved these changes

2021-12-20 17:19 UTC, merged