Use event caption for opengraph description
svthalia/concrexit pull request #2093
Opened 2021-12-16 11:05 UTC by JobDoesburg

### Summary
Use event caption for opengraph description

### How to test
1. Visit the event details page
2. Verify that the `og:description` uses the caption

For example, use https://www.opengraph.xyz

2021-12-16 16:39 UTC, se-bastiaan approved these changes

2021-12-16 16:40 UTC, se-bastiaan requested changes
You should probably add a fallback to the description in this case.

2021-12-17 18:09 UTC, se-bastiaan approved these changes

2021-12-20 16:21 UTC, ColonelPhantom approved these changes

2021-12-20 16:54 UTC, merged