Fix newsletter for up to three local partners
svthalia/concrexit pull request #2105
Opened 2021-12-21 15:09 UTC by wdoeland

Closes #2041

### Summary
Not all local partners were shown in the newsletter. Now they are all shown.

### How to test
Steps to test the changes you made:
1. Create a new newsletter and preview it 'on the site'.
2. Make 0 partners local partner
3. Refresh and see 0 local partners in the newsletter
4. Do steps 2-3 with 0, 1, 2 and 3 partners and see 0, 1, 2 and 3 local partners in the newsletter.

2021-12-21 15:11 UTC, SebastiaanSafeguard requested changes
-

2021-12-21 15:12 UTC, se-bastiaan requested changes
With this approach any change to the partner logos as uploaded by an administrator could break versions of the newsletter when opened at a later time. I would suggest trying to include them by using base64 images.

2021-12-21 15:18 UTC, wdoeland commented
> With this approach any change to the partner logos as uploaded by an administrator could break versions of the newsletter when opened at a later time. I would suggest trying to include them by using base64 images.

A few things on this:
- I think base64 images don't work in a lot of email clients. 
- Partners (and their images) are not deleted but they are just not set to be active anymore.
- I also don't think it's a big issue if an image (with an alt text!) doesn't display properly after a while in a weekly newsletter, does anyone reread these? It's much more important to make sure the email works properly now.

2021-12-22 00:10 UTC, pingiun commented
> I think base64 images don't work in a lot of email clients.

I don't think that's true

2021-12-22 13:18 UTC, pingiun commented on website/newsletters/templates/newsletters/email.html
> +                            <img src="{{ main_partner.logo.url }}" height="95" style="height: 95px;" alt="{{ main_partner.name }}"/>
This should include the baseurl. Relative urls don't work in emails

2021-12-22 15:55 UTC, pingiun commented
> * Partners (and their images) are not deleted but they are just not set to be active anymore

When an image is changed for a partner the url can also change. I don't think we delete the old image. What do you think @se-bastiaan should we just merge this?

2021-12-22 19:05 UTC, se-bastiaan commented
Other small note: the text version of the newsletter has not been changed yet.

2021-12-22 19:12 UTC, se-bastiaan commented on website/newsletters/templates/newsletters/email.html
> +                            <img src="{% baseurl %}{{ main_partner.logo.url }}" height="95" style="height: 95px;" alt="{{ main_partner.name }}"/>
Can you use the thumbnail instead of the full image

2021-12-22 19:12 UTC, se-bastiaan commented on website/newsletters/templates/newsletters/email.html
> +                            <img src="{% baseurl %}{{ main_partner.logo.url }}" height="95" style="height: 95px;" alt="{{ main_partner.name }}"/>
`{% thumbnail main_partner.logo THUMBNAIL_SIZE_MEDIUM fit=False %}`

2021-12-22 19:22 UTC, se-bastiaan commented on website/newsletters/templates/newsletters/email.html
> +    {% if local_partners.all %}
```suggestion
    {% if local_partners.exists %}
```

Dit is een hele zware query die niet nodig is :)

2021-12-22 20:18 UTC, se-bastiaan approved these changes

2021-12-22 20:22 UTC, merged