Make profile fields blankable
svthalia/concrexit pull request #2638
Opened 2022-11-02 19:25 UTC by pingiun

Closes #2629 

### Summary
Make profile fields blankable

### How to test
Multiple flows should be tested:

# Admin flow
1. Have user with profile.
2. Admin removes address fields
3. This is allowed

# User flow
1. Be user with profile
2. Try to remove address field
3. This is not allowed

# Dataminimisation
1. Have old user with profile
2. User is minimised by dataminimisation management command
3. Old profile now has blank fields everywhere and is still editable by the admin

2022-11-10 21:15 UTC, JobDoesburg requested changes

2022-11-10 21:15 UTC, JobDoesburg commented on website/members/services.py
> +            profile.birthday = None
In website/members/models/profile.py line 276-277 the `is_minimised` property should also be rewritten now

2022-12-22 10:57 UTC, JobDoesburg commented on website/members/services.py
> +            profile.birthday = None
> In website/members/models/profile.py line 276-277 the `is_minimised` property should also be rewritten now

Or maybe we should introduce a `is_minimised` field, and clean the model to only allow null fields if `is_minised` is `True`

2023-01-25 19:06 UTC, pingiun commented on website/members/models/profile.py
> +        if not self.is_minimized and not (
No

2023-01-25 19:29 UTC, JobDoesburg approved these changes

2023-01-25 19:29 UTC, merged