fix missing organiser email
svthalia/concrexit pull request #2808
Opened 2023-02-08 19:34 UTC by Pokemaster69

Closes #ISSUE

### Summary
Remove the no longer existing organiser_name and organiser_mail from the email template
Add list of organiser emails to the email model
Add variable with comma seperate list for email template

### How to test
Create an event (with 1 open registration)
register 1 user and put another user in the queue
deregister original user
observer the email in terminal and see it no longer says "you can reach   at  .

2023-02-08 20:30 UTC, JobDoesburg commented on website/events/emails.py
> +
You probably want to `", ".join()` this list, otherwise it will actually be formatted as a python list

2023-02-08 20:31 UTC, JobDoesburg requested changes
see comment

2023-02-08 21:13 UTC, ColonelPhantom commented
There's also an automatic email for when the limit is increased in `more_places_email.txt` (`def notify_waiting():`).

I think that email has the same wrong/outdated code, so you should add the same changes there.

2023-02-09 08:46 UTC, JobDoesburg approved these changes

2023-02-09 08:47 UTC, merged