Add facedetection api endpoints
svthalia/concrexit pull request #3218
Opened 2023-06-29 10:46 UTC by JeeVee11

Closes #3101 

### Summary
Add API endpoints to view the users facedetection photos and see/update their reference faces.

### How to test
Steps to test the changes you made:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

2024-05-15 19:22 UTC, ColonelPhantom requested changes
We should probably deduplicate the logic here.

2024-05-15 19:22 UTC, ColonelPhantom commented on website/facedetection/api/v2/views.py
> +    def get_queryset(self):
The original view has the same logic. We should probably deduplicate that so that changing this logic is not painful.

2024-05-22 18:11 UTC, T8902 approved these changes

2024-05-22 18:11 UTC, T8902 commented on website/facedetection/api/v2/views.py
> +            raise PermissionDenied(detail="You need to be a member to use this feaure.")
```suggestion
            raise PermissionDenied(detail="You need to be a member to use this feature.")
```

2024-05-23 05:44 UTC, merged