Committee chair permission
svthalia/concrexit pull request #3383
Opened 2023-09-27 20:48 UTC by Noah-marc

Closes #ISSUE

### Summary
Added the option to add permissions that only a chair should have to MemberGroups and for  MemberGroupMemberships to have those chair permissions. Also for all existing MemberGroupMemberships that are already marked as chair also automatically have chair permissions 

### How to test
Steps to test the changes you made:
1. Go to a Committee or Society in the admin, select the desired chair-permissions in the respective field and save them
2. Go to the MemberGroupMembership admin and click on a MemberGroupMembership that you want to give chair permissions, mark the checkmark has_chair_permissions and save
3. Make sure that the member connected to that MemberGroupMembership has no other permissions form other MemberGroups
4. Log into that user, go to the admin page and try do the things that you gave permissions to do. It should work then
5. Log into a user that is part of that same MemberGroup and where his Membership does not have those permissions
6. Try to do the same actions as in 4. This time it should fail

2023-09-28 14:24 UTC, DeD1rk reviewed
Looks good as far as I can tell. Is there any chance you could test the migration with a local postgres db (as runpython + field changes has been giving issues on postgres in the past that didn't occur on sqlite3)? 
And maybe it would be nice if someone else also looks at this as I'm biased on the actual permissions backend changes.

2023-09-28 14:27 UTC, DeD1rk commented
Oh and yes I see this includes an unrelated commit  (86978fcd087429a3001142cabfcc1576822c2d64) that's causing a conflict. So could you rebase it out? (`git rebase -i origin/master` and `drop` the photo.hidden commit)

2023-10-03 12:14 UTC, T8902 commented on website/photos/admin.py
> -    list_filter = ("album", "hidden")
I think removing the hidden picture feature would be better in a different pull request.

2023-10-03 12:15 UTC, T8902 requested changes
Removing hidden picture feature should be in a different branch/pull request in my opinion

2023-10-04 11:23 UTC, DeD1rk commented
I did the rebase

2023-10-05 05:34 UTC, DeD1rk approved these changes

2023-10-05 05:35 UTC, merged